---
output: github_document
title: Advent of Code - Day 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

```{r}
# devtools::install_github("benjaminguinaudeau/adventr")
suppressMessages(library(dplyr))
library(stringr)
library(purrr)
library(adventr)
```

## Problem data

```{r}
input <- read_advent_of_code(4) %>%
  glimpse
```

## Data Wrangling

```{r}
dt <- input %>%
  paste(collapse = "\n") %>%
  str_split("\n\n") %>%
  .[[1]] %>% 
  map_dfr(~{
    .x %>%
      str_split("\\s") %>%
      .[[1]] %>%
      map_dfc(~{
        tibble::tibble(!!str_extract(.x, "^.+(?=\\:)") := str_extract(.x, "(?<=\\:).+$"))
      })
    
  })

```

## Problem 1

```{r}
valid_1 <- dt %>%
  filter_at(vars(hcl, ecl, iyr, pid, hgt, eyr, byr), ~!is.na(.x)) %>%
  glimpse
```

```{r, eval = F}
submit_to_advent_of_code(answer = 196, day = 4, level = 1)
```

## Problem 2

```{r}

btwn <- function(x, low, high){
  return(x >= low & x <= high)
}

valid_1 %>%
  # Years
  filter(str_detect(byr, "^\\d{4}$") & btwn(as.numeric(byr), 1920, 2002)) %>%
  filter(str_detect(iyr, "^\\d{4}$") & btwn(as.numeric(iyr), 2010, 2020)) %>%
  filter(str_detect(eyr, "^\\d{4}$") & btwn(as.numeric(eyr), 2020, 2030)) %>%
  # Height
  filter(str_detect(hgt, "\\d+(cm|in)"))%>%
  filter(ifelse(str_detect(hgt, "cm"), 
                btwn(as.numeric(str_extract(hgt, "\\d+")), 150, 193),
                btwn(as.numeric(str_extract(hgt, "\\d+")), 59, 76))) %>%
  # Colors
  filter(str_detect(hcl, "#[[0-9a-f]]{6}")) %>%
  filter(ecl %in% c("amb", "blu", "brn", "gry", "grn", "hzl", "oth")) %>%
  # Passport ID
  filter(str_detect(str_pad(pid, "0", 9, side = "right"), "^\\d{9}$"))


```
```{r, eval = F}
submit_to_advent_of_code(answer = 114, day = 4, level = 2)
```

