---
output: github_document
title: Advent of Code - Day 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

```{r}
# devtools::install_github("benjaminguinaudeau/adventr")
suppressMessages(library(dplyr))
library(stringr)
library(purrr)
library(adventr)
```

## Problem data

```{r}
input <- read_advent_of_code(5) %>%
  glimpse
```


## Data Wrangling

```{r}
base_row <- c(64, 32, 16, 8, 4, 2, 1)
base_side <- c(4, 2, 1)

plane_dt <- tibble::tibble(input) %>%
  mutate(
    row = input %>%
      str_extract("^.{7}") %>%
      str_extract_all(".") %>% 
      map_dbl(~{
        sum(ifelse(.x == "F", 0, 1)*base_row)
      }), 
    side = input %>%
      str_extract(".{3}$") %>%
      str_extract_all(".") %>% 
      map_dbl(~{
        sum(ifelse(.x == "L", 0, 1)*base_side)
      }), 
    seat_id = row*8 + side
  )
```


## Task 1

```{r}
plane_dt %>%
  summarise(seat_id_max = max(seat_id, na.rm = T))
```
```{r, eval = F}
submit_to_advent_of_code(888, day = 5, level = 1)
```

## Task 2

```{r}
missing_seat <- tidyr::expand_grid(row = 0:127, side = 0:7) %>%
  mutate(seat_id = row*8 + side) %>%
  filter(!seat_id %in% plane_dt$seat_id)

missing_seat %>%
  arrange(seat_id) %>%
  filter((seat_id + 1) %in% plane_dt$seat_id & (seat_id - 1) %in% plane_dt$seat_id)

```
```{r, eval = F}
submit_to_advent_of_code(522, day = 5, level = 2)
```
